name: Build BK7238 HLW8112

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build BK7238 HLW8112
        run: |
          make OpenBK7238 VARIANT=hlw8112

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenBK7238_HLW8112
          path: output/**
